GET http://church-manage-app:8081/api/events
Accept: application/json

### List events filtered by createdAfter and churchId
GET http://localhost:8081/api/events?createdAfter=2025-11-01T00:00:00Z&churchId=church-1
Accept: application/json

### Create a new event
POST http://localhost:8081/api/events
Content-Type: application/json

{
  "churchId": "church-1",
  "name": "Culto Dominical",
  "description": "Culto semanal",
  "startDatetime": "2025-11-30T10:00:00Z",
  "endDatetime": "2025-11-30T12:00:00Z",
  "location": "Igreja Central",
  "createdBy": "admin"
}

### Add a participant to an event
POST http://localhost:8081/api/events/participants
Content-Type: application/json

{
  "eventId": "d94831ba-0206-499b-a37e-1498918397ee",
  "memberId": "member-1",
  "role": "volunteer",
  "registeredAt": "2025-11-25T10:00:00Z"
}

### List participants of an event
GET http://localhost:8081/api/events/d94831ba-0206-499b-a37e-1498918397ee/participants
Accept: application/json

###
GET http://localhost:8081/api/events/user/member-1
Accept: application/json

### Update an event
PUT http://localhost:8080/api/events/<event-id>
Content-Type: application/json

{
  "churchId": "church-1",
  "name": "Culto Atualizado",
  "description": "Descrição atualizada",
  "startDatetime": "2025-12-01T10:00:00Z",
  "endDatetime": "2025-12-01T12:00:00Z",
  "location": "Nova Localização",
  "createdBy": "admin"
}

### Delete an event
DELETE http://localhost:8080/api/events/<event-id>
